### ISSUE TITLE
Dynamic Contents not displayed in Admin App in default

### ISSUE THREAD

**Issue by acanli** [Sitefinity/sitefinity-admin-app-extensions#298]
Hello,

First of all, I tried to checkout my Sitefinity version but it did not work (git checkout 11.2.6937.0). And then I have used the similar version and checkout was successful (git checkout 11.2.6900.0). I don't know if this is relevant with this but I've managed to connect Admin App (localhost:3000) to my SF instance (localhost:41517), I also managed to login to SF instance but when I click "Content" tab in the Admin app instance, I only see blank page instead of listing dynamic modules/contents. So auth operation is successful but there is still CORS issue which is blocking my connection. (I have already configured CORS settings on Sitefinity Settings and gave permission to localhost:3000). 

I have an error on console as below. I'm not sure if this is related or not.

![image](https://user-images.githubusercontent.com/56534910/111464334-b123e900-8731-11eb-838a-0ac30be81196.png)

And my "Content" tab looks like below

![image](https://user-images.githubusercontent.com/56534910/111464381-c3058c00-8731-11eb-8ad2-b93c18c59d46.png)

We're using Sitefinity for couple of years and trying to enable Admin App.

Kind Regards,
Anil

**Comment by Novkirishki** [comment]
Hi @acanli , 

Thanks for contacting us! We have missed to add a tag for the specific Sitefinity version you are using. Everything should be fixed now. You can try again executing `git checkout 11.2.6937.0` and running the application.

All the best!

**Comment by acanli** [comment]
Hi @Novkirishki,

Thanks for your quick action. I tried to checkout but still has the same issue. Should I reclone it and try again maybe? The error message is below.

error: pathspec '11.2.6937.0' did not match any file(s) known to git

Kind Regards,
Anil

**Comment by Novkirishki** [comment]
Hi @acanli , 

did you do `git fetch` to get the new tags before the checkout?

**Comment by acanli** [comment]
Hi @Novkirishki,

My bad I did it and managed to get the tag. However, issue still continues.

**Comment by Novkirishki** [comment]
Hi @acanli ,

I just tested the scenario in a new 11.2.6937.0 project and everything works fine. It is possible that you have some customizations that might be causing the errors. 

I advise you to contact the Sitefinity support team and open a ticket, they should be able to identify the cause of the problem.

If you are getting the same errors in your Sitefinity instance ("sitefinitylocalhost/Sitefinity/AdminApp") it means the issue is not related to the AdminApp extensibility so I am closing the issue.
